Have looked at Scribe but that relies on proper oAuth worflow (Twitter/LinkedIn etc).
signpost seems to be a nice simple implementation. However, it
expects apache HttpRequests when signing:

java.lang.IllegalArgumentException: This consumer expects requests of type org.apache.http.HttpRequest

Will see if cz.msebera.android has helper classes for doing the conversion. Cannot use directly http commons httpclient since Android requires async/non-main thread httpclient calls. cz.msebera.android takes care of that behind the scenes